name: test-actions-workflow
on: [push, workflow_dispatch]

jobs:
    testing-actions-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: ls -a
            - name: clone repo
              uses: actions/checkout@v6
            - name: list after clone
              run: ls -a
    install-node-and-run-file:
        runs-on: ubuntu-latest
        steps:
            - name: list pre node version
              run: node -v
            - name: install node
              uses: actions/setup-node@v6
              with:
                node-version: '24'
            - name: list after node installation
              run: node -v


            
