name: deploy-client
on:
  push:
    branches: ['master', 'dev']
  workflow_dispatch:

jobs:
  get-changed-files:
    uses: ./.github/workflows/detect-changes.yml

  deploy-client:
    needs: get-changed-files
    if: ${{ github.ref_name == 'master' && needs.get-changed-files.outputs.client == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7
      - name: deploy client
        run: echo "Deploying client because changes were detected in the clients directory."



  


            
