name: monorepo-actions
on:
  push:
    branches: ['master', 'test']

jobs:
  my-env-job:
    # environment: ${{ github.ref_name == 'master' && 'PROD' || 'TEST' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref_name }}
      - run: echo ${{secrets.AWS_SECRET}}

  my-aws-cf-job:
    if: ${{ github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v7  
      - run: pwd
      - run: ls -a
      - run: echo "push to aws coudfront"
      - name: Show changed files
        run: "git diff --name-only HEAD^ HEAD"

  


            
