name: sshpass-actions

on:
  push:
    branches: ['master', 'main']
  workflow_dispatch:


jobs:
  deploy-to-server:
    environment: PROD
    runs-on: ubuntu-latest

    steps:
      - name: Check for sshpass binary file
        run: |
          if ! command -v sshpass &> /dev/null; then
            echo "sshpass could not be found, installing..."
            sudo apt-get update
            sudo apt-get install -y sshpass
          else
            echo "sshpass is already installed."
            sshpass -V
          fi

      - name: Create index.js
        run: echo 'console.log("Hello World! 5:59");' > index.js

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H pcvm.printcampus.in >> ~/.ssh/known_hosts

      - name: Copy file to server
        env:
          SSHPASS: ${{ secrets.PCVM_SSH_PASSWORD }}
        run: |
          sshpass -e scp \
            ./index.js \
            ${{ secrets.SSH_USER }}@${{ secrets.PCVM_SSH_HOST }}:${{ secrets.SSH_VM_HOME_PATH }}/index.js

  