name: test-workflow
on: [push, workflow_dispatch]

jobs:
    testing-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run: ls -a
            - name: present directory
              run: pwd
            - name: list users
              run: ls /home
            - name: sudo root
              run: sudo -i

    create-and-run-file:
        runs-on: ubuntu-latest
        steps:
            - name: create file
              run: echo 'console.log("Hello World!");' > app.js
            - name: node -v
              run: node -v
            - name: run file content
              run: node app.js

    print-sys-info:
        runs-on: ubuntu-latest
        needs: create-and-run-file
        steps:
            - name: list files
              run: |
                echo "Listing files:"
                ls -a

            
