name: run-cmds-without-name
on: [push, workflow_dispatch]

jobs:
    run-cmds-without-name:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ toJSON(env) }}"
            - run: echo "${{ toJSON(vars) }}"
            - run: echo "${{ toJSON(secrets) }}"
            - run: echo "${{ toJSON(runner) }}"


            
